[versions]
ksp = "2.0.0-1.0.21"
kotlinxCoroutines = "1.9.0-RC"
junit = "4.13.2"
kotlinPoet = "1.18.1"
truth = "1.4.2"
stratify = "1.1.0-beta16"
mustache = "0.9.10"

[libraries]
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
ksp-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp"}
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlin-poet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinPoet" }
kotlin-poet-ksp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "kotlinPoet"}
stratify = { module = "io.github.mattshoe.shoebox:Stratify", version.ref = "stratify" }
stratify-test = { module = "io.github.mattshoe.shoebox:Stratify.Test", version.ref = "stratify" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
mustache = { module = "com.github.spullara.mustache.java:compiler", version.ref = "mustache"}

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

